services:
  - type: web
    name: flask-blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: frankfurt
    plan: free
    branch: master
    autoDeploy: true
